/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HowitworksRouteImport } from './routes/howitworks'
import { Route as FeaturesRouteImport } from './routes/features'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as AppSettingsIndexRouteImport } from './routes/app/settings/index'
import { Route as AppNotesIndexRouteImport } from './routes/app/notes/index'
import { Route as AppInterviewsIndexRouteImport } from './routes/app/interviews/index'
import { Route as AppApplicationsIndexRouteImport } from './routes/app/applications/index'
import { Route as DemoStartServerFuncsRouteImport } from './routes/demo/start.server-funcs'
import { Route as DemoStartApiRequestRouteImport } from './routes/demo/start.api-request'
import { Route as DemoApiNamesRouteImport } from './routes/demo/api.names'
import { Route as AppCompaniesCompaniesRouteImport } from './routes/app/companies/companies'
import { Route as DemoStartSsrIndexRouteImport } from './routes/demo/start.ssr.index'
import { Route as DemoStartSsrSpaModeRouteImport } from './routes/demo/start.ssr.spa-mode'
import { Route as DemoStartSsrFullSsrRouteImport } from './routes/demo/start.ssr.full-ssr'
import { Route as DemoStartSsrDataOnlyRouteImport } from './routes/demo/start.ssr.data-only'

const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HowitworksRoute = HowitworksRouteImport.update({
  id: '/howitworks',
  path: '/howitworks',
  getParentRoute: () => rootRouteImport,
} as any)
const FeaturesRoute = FeaturesRouteImport.update({
  id: '/features',
  path: '/features',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/app/',
  path: '/app/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSettingsIndexRoute = AppSettingsIndexRouteImport.update({
  id: '/app/settings/',
  path: '/app/settings/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppNotesIndexRoute = AppNotesIndexRouteImport.update({
  id: '/app/notes/',
  path: '/app/notes/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppInterviewsIndexRoute = AppInterviewsIndexRouteImport.update({
  id: '/app/interviews/',
  path: '/app/interviews/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppApplicationsIndexRoute = AppApplicationsIndexRouteImport.update({
  id: '/app/applications/',
  path: '/app/applications/',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartServerFuncsRoute = DemoStartServerFuncsRouteImport.update({
  id: '/demo/start/server-funcs',
  path: '/demo/start/server-funcs',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartApiRequestRoute = DemoStartApiRequestRouteImport.update({
  id: '/demo/start/api-request',
  path: '/demo/start/api-request',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoApiNamesRoute = DemoApiNamesRouteImport.update({
  id: '/demo/api/names',
  path: '/demo/api/names',
  getParentRoute: () => rootRouteImport,
} as any)
const AppCompaniesCompaniesRoute = AppCompaniesCompaniesRouteImport.update({
  id: '/app/companies/companies',
  path: '/app/companies/companies',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartSsrIndexRoute = DemoStartSsrIndexRouteImport.update({
  id: '/demo/start/ssr/',
  path: '/demo/start/ssr/',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartSsrSpaModeRoute = DemoStartSsrSpaModeRouteImport.update({
  id: '/demo/start/ssr/spa-mode',
  path: '/demo/start/ssr/spa-mode',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartSsrFullSsrRoute = DemoStartSsrFullSsrRouteImport.update({
  id: '/demo/start/ssr/full-ssr',
  path: '/demo/start/ssr/full-ssr',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartSsrDataOnlyRoute = DemoStartSsrDataOnlyRouteImport.update({
  id: '/demo/start/ssr/data-only',
  path: '/demo/start/ssr/data-only',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/features': typeof FeaturesRoute
  '/howitworks': typeof HowitworksRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/app': typeof AppIndexRoute
  '/app/companies/companies': typeof AppCompaniesCompaniesRoute
  '/demo/api/names': typeof DemoApiNamesRoute
  '/demo/start/api-request': typeof DemoStartApiRequestRoute
  '/demo/start/server-funcs': typeof DemoStartServerFuncsRoute
  '/app/applications': typeof AppApplicationsIndexRoute
  '/app/interviews': typeof AppInterviewsIndexRoute
  '/app/notes': typeof AppNotesIndexRoute
  '/app/settings': typeof AppSettingsIndexRoute
  '/demo/start/ssr/data-only': typeof DemoStartSsrDataOnlyRoute
  '/demo/start/ssr/full-ssr': typeof DemoStartSsrFullSsrRoute
  '/demo/start/ssr/spa-mode': typeof DemoStartSsrSpaModeRoute
  '/demo/start/ssr': typeof DemoStartSsrIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/features': typeof FeaturesRoute
  '/howitworks': typeof HowitworksRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/app': typeof AppIndexRoute
  '/app/companies/companies': typeof AppCompaniesCompaniesRoute
  '/demo/api/names': typeof DemoApiNamesRoute
  '/demo/start/api-request': typeof DemoStartApiRequestRoute
  '/demo/start/server-funcs': typeof DemoStartServerFuncsRoute
  '/app/applications': typeof AppApplicationsIndexRoute
  '/app/interviews': typeof AppInterviewsIndexRoute
  '/app/notes': typeof AppNotesIndexRoute
  '/app/settings': typeof AppSettingsIndexRoute
  '/demo/start/ssr/data-only': typeof DemoStartSsrDataOnlyRoute
  '/demo/start/ssr/full-ssr': typeof DemoStartSsrFullSsrRoute
  '/demo/start/ssr/spa-mode': typeof DemoStartSsrSpaModeRoute
  '/demo/start/ssr': typeof DemoStartSsrIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/features': typeof FeaturesRoute
  '/howitworks': typeof HowitworksRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/app/': typeof AppIndexRoute
  '/app/companies/companies': typeof AppCompaniesCompaniesRoute
  '/demo/api/names': typeof DemoApiNamesRoute
  '/demo/start/api-request': typeof DemoStartApiRequestRoute
  '/demo/start/server-funcs': typeof DemoStartServerFuncsRoute
  '/app/applications/': typeof AppApplicationsIndexRoute
  '/app/interviews/': typeof AppInterviewsIndexRoute
  '/app/notes/': typeof AppNotesIndexRoute
  '/app/settings/': typeof AppSettingsIndexRoute
  '/demo/start/ssr/data-only': typeof DemoStartSsrDataOnlyRoute
  '/demo/start/ssr/full-ssr': typeof DemoStartSsrFullSsrRoute
  '/demo/start/ssr/spa-mode': typeof DemoStartSsrSpaModeRoute
  '/demo/start/ssr/': typeof DemoStartSsrIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/features'
    | '/howitworks'
    | '/login'
    | '/pricing'
    | '/app'
    | '/app/companies/companies'
    | '/demo/api/names'
    | '/demo/start/api-request'
    | '/demo/start/server-funcs'
    | '/app/applications'
    | '/app/interviews'
    | '/app/notes'
    | '/app/settings'
    | '/demo/start/ssr/data-only'
    | '/demo/start/ssr/full-ssr'
    | '/demo/start/ssr/spa-mode'
    | '/demo/start/ssr'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/features'
    | '/howitworks'
    | '/login'
    | '/pricing'
    | '/app'
    | '/app/companies/companies'
    | '/demo/api/names'
    | '/demo/start/api-request'
    | '/demo/start/server-funcs'
    | '/app/applications'
    | '/app/interviews'
    | '/app/notes'
    | '/app/settings'
    | '/demo/start/ssr/data-only'
    | '/demo/start/ssr/full-ssr'
    | '/demo/start/ssr/spa-mode'
    | '/demo/start/ssr'
  id:
    | '__root__'
    | '/'
    | '/features'
    | '/howitworks'
    | '/login'
    | '/pricing'
    | '/app/'
    | '/app/companies/companies'
    | '/demo/api/names'
    | '/demo/start/api-request'
    | '/demo/start/server-funcs'
    | '/app/applications/'
    | '/app/interviews/'
    | '/app/notes/'
    | '/app/settings/'
    | '/demo/start/ssr/data-only'
    | '/demo/start/ssr/full-ssr'
    | '/demo/start/ssr/spa-mode'
    | '/demo/start/ssr/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FeaturesRoute: typeof FeaturesRoute
  HowitworksRoute: typeof HowitworksRoute
  LoginRoute: typeof LoginRoute
  PricingRoute: typeof PricingRoute
  AppIndexRoute: typeof AppIndexRoute
  AppCompaniesCompaniesRoute: typeof AppCompaniesCompaniesRoute
  DemoApiNamesRoute: typeof DemoApiNamesRoute
  DemoStartApiRequestRoute: typeof DemoStartApiRequestRoute
  DemoStartServerFuncsRoute: typeof DemoStartServerFuncsRoute
  AppApplicationsIndexRoute: typeof AppApplicationsIndexRoute
  AppInterviewsIndexRoute: typeof AppInterviewsIndexRoute
  AppNotesIndexRoute: typeof AppNotesIndexRoute
  AppSettingsIndexRoute: typeof AppSettingsIndexRoute
  DemoStartSsrDataOnlyRoute: typeof DemoStartSsrDataOnlyRoute
  DemoStartSsrFullSsrRoute: typeof DemoStartSsrFullSsrRoute
  DemoStartSsrSpaModeRoute: typeof DemoStartSsrSpaModeRoute
  DemoStartSsrIndexRoute: typeof DemoStartSsrIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/howitworks': {
      id: '/howitworks'
      path: '/howitworks'
      fullPath: '/howitworks'
      preLoaderRoute: typeof HowitworksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features': {
      id: '/features'
      path: '/features'
      fullPath: '/features'
      preLoaderRoute: typeof FeaturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/settings/': {
      id: '/app/settings/'
      path: '/app/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/notes/': {
      id: '/app/notes/'
      path: '/app/notes'
      fullPath: '/app/notes'
      preLoaderRoute: typeof AppNotesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/interviews/': {
      id: '/app/interviews/'
      path: '/app/interviews'
      fullPath: '/app/interviews'
      preLoaderRoute: typeof AppInterviewsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/applications/': {
      id: '/app/applications/'
      path: '/app/applications'
      fullPath: '/app/applications'
      preLoaderRoute: typeof AppApplicationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/server-funcs': {
      id: '/demo/start/server-funcs'
      path: '/demo/start/server-funcs'
      fullPath: '/demo/start/server-funcs'
      preLoaderRoute: typeof DemoStartServerFuncsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/api-request': {
      id: '/demo/start/api-request'
      path: '/demo/start/api-request'
      fullPath: '/demo/start/api-request'
      preLoaderRoute: typeof DemoStartApiRequestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/api/names': {
      id: '/demo/api/names'
      path: '/demo/api/names'
      fullPath: '/demo/api/names'
      preLoaderRoute: typeof DemoApiNamesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/companies/companies': {
      id: '/app/companies/companies'
      path: '/app/companies/companies'
      fullPath: '/app/companies/companies'
      preLoaderRoute: typeof AppCompaniesCompaniesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/ssr/': {
      id: '/demo/start/ssr/'
      path: '/demo/start/ssr'
      fullPath: '/demo/start/ssr'
      preLoaderRoute: typeof DemoStartSsrIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/ssr/spa-mode': {
      id: '/demo/start/ssr/spa-mode'
      path: '/demo/start/ssr/spa-mode'
      fullPath: '/demo/start/ssr/spa-mode'
      preLoaderRoute: typeof DemoStartSsrSpaModeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/ssr/full-ssr': {
      id: '/demo/start/ssr/full-ssr'
      path: '/demo/start/ssr/full-ssr'
      fullPath: '/demo/start/ssr/full-ssr'
      preLoaderRoute: typeof DemoStartSsrFullSsrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/ssr/data-only': {
      id: '/demo/start/ssr/data-only'
      path: '/demo/start/ssr/data-only'
      fullPath: '/demo/start/ssr/data-only'
      preLoaderRoute: typeof DemoStartSsrDataOnlyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FeaturesRoute: FeaturesRoute,
  HowitworksRoute: HowitworksRoute,
  LoginRoute: LoginRoute,
  PricingRoute: PricingRoute,
  AppIndexRoute: AppIndexRoute,
  AppCompaniesCompaniesRoute: AppCompaniesCompaniesRoute,
  DemoApiNamesRoute: DemoApiNamesRoute,
  DemoStartApiRequestRoute: DemoStartApiRequestRoute,
  DemoStartServerFuncsRoute: DemoStartServerFuncsRoute,
  AppApplicationsIndexRoute: AppApplicationsIndexRoute,
  AppInterviewsIndexRoute: AppInterviewsIndexRoute,
  AppNotesIndexRoute: AppNotesIndexRoute,
  AppSettingsIndexRoute: AppSettingsIndexRoute,
  DemoStartSsrDataOnlyRoute: DemoStartSsrDataOnlyRoute,
  DemoStartSsrFullSsrRoute: DemoStartSsrFullSsrRoute,
  DemoStartSsrSpaModeRoute: DemoStartSsrSpaModeRoute,
  DemoStartSsrIndexRoute: DemoStartSsrIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
